extern crate cbindgen;

use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let package_name = env::var("CARGO_PKG_NAME").unwrap();

    // Only generate header for the s1_driver_rust package
    if package_name == "s1_driver_rust" {
        let output_file = PathBuf::from(&crate_dir)
            .join("include")
            .join("s1_driver")
            .join("rust_interface.h");

        let config = cbindgen::Config {
            language: cbindgen::Language::C,
            ..Default::default()
        };

        cbindgen::Builder::new()
            .with_crate(crate_dir)
            .with_config(config)
            .with_header("/* Auto-generated by cbindgen. Do not edit. */")
            .with_include_guard("RUST_INTERFACE_H_")
            .generate()
            .expect("Unable to generate bindings")
            .write_to_file(output_file);
    }
}
